### ISSUE TITLE
Auto-terminate of container should use new HCS capabilities

### ISSUE THREAD

**Issue by jstarks** [Microsoft/dotnet-computevirtualization#5]
HCS now can auto-terminate a container on last handle being closed. We should have KillOnClose use this behavior instead of doing it manually within the C# code so that this works even if the Container object is never disposed.

**Comment by jterry75** [comment]
@swernli 

The property is now:

``` C#
[DataMember(EmitDefaultValue=false)]
public bool TerminateOnLastHandleClosed
{
    get;
    set;
}
```

on schema/Compute/ContainerSettings

**Comment by swernli** [comment]
This was checked in with alpha4 version.
